//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDental.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDental.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] canadiancarriers {
            get {
                object obj = ResourceManager.GetObject("canadiancarriers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CDAErrorMessagesEn {
            get {
                object obj = ResourceManager.GetObject("CDAErrorMessagesEn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CDAErrorMessagesFr {
            get {
                object obj = ResourceManager.GetObject("CDAErrorMessagesFr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteX {
            get {
                object obj = ResourceManager.GetObject("deleteX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editPencil {
            get {
                object obj = ResourceManager.GetObject("editPencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Report Name=&quot;&quot;&gt;
        ///  &lt;Description&gt;
        ///  &lt;/Description&gt;
        ///  &lt;Author&gt;
        ///  &lt;/Author&gt;
        ///  &lt;PageHeight&gt;11in&lt;/PageHeight&gt;
        ///  &lt;PageWidth&gt;8.5in&lt;/PageWidth&gt;
        ///  &lt;Width&gt;7.5in&lt;/Width&gt;
        ///  &lt;TopMargin&gt;.25in&lt;/TopMargin&gt;
        ///  &lt;LeftMargin&gt;.25in&lt;/LeftMargin&gt;
        ///  &lt;RightMargin&gt;.25in&lt;/RightMargin&gt;
        ///  &lt;BottomMargin&gt;.25in&lt;/BottomMargin&gt;
        ///  &lt;DataSets&gt;
        ///    &lt;DataSet Name=&quot;Assets&quot;&gt;
        ///      &lt;Query&gt;
        ///        &lt;DataSourceName&gt;DS1&lt;/DataSourceName&gt;
        ///        &lt;Timeout&gt;10&lt;/Timeout&gt;
        ///        &lt;CommandText&gt;SELECT De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportAccountingBalanceSheet {
            get {
                return ResourceManager.GetString("ReportAccountingBalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Report Name=&quot;&quot;&gt;
        ///  &lt;Description&gt;
        ///  &lt;/Description&gt;
        ///  &lt;Author&gt;
        ///  &lt;/Author&gt;
        ///  &lt;PageHeight&gt;11in&lt;/PageHeight&gt;
        ///  &lt;PageWidth&gt;8.5in&lt;/PageWidth&gt;
        ///  &lt;Width&gt;7.5in&lt;/Width&gt;
        ///  &lt;TopMargin&gt;.25in&lt;/TopMargin&gt;
        ///  &lt;LeftMargin&gt;.25in&lt;/LeftMargin&gt;
        ///  &lt;RightMargin&gt;.25in&lt;/RightMargin&gt;
        ///  &lt;BottomMargin&gt;.25in&lt;/BottomMargin&gt;
        ///  &lt;DataSets&gt;
        ///    &lt;DataSet Name=&quot;Data&quot;&gt;
        ///      &lt;Query&gt;
        ///        &lt;DataSourceName&gt;DS1&lt;/DataSourceName&gt;
        ///        &lt;Timeout&gt;10&lt;/Timeout&gt;
        ///        &lt;CommandText&gt;SELECT acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportAccountingGenLedger {
            get {
                return ResourceManager.GetString("ReportAccountingGenLedger", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
